import { Buku } from '@/types/database';

export const BOOKS_100: Buku[] = [
  // =========================================================================
  // 1. KOMPUTER & PEMROGRAMAN (KG0) - 20 BUKU
  // =========================================================================
  {
    isbn: '978-602-04-9988-0',
    barcode_eksemplar: 'PS-2600001',
    judul: 'Belajar Pemrograman Web Modern & Database Supabase',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 15,
    foto: '/buku/1788324109_logo.jpg',
    maks_pinjam_per_anggota: 2,
    ddc: '005.133',
    lokasi_rak: 'R-A1',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Panduan komprehensif arsitektur web modern dengan Next.js, TypeScript, dan Supabase.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0101-2',
    barcode_eksemplar: 'PS-2600002',
    judul: 'Clean Code: Panduan Menulis Kode yang Rapi dan Terstruktur',
    tahun: 2023,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 10,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '005.1',
    lokasi_rak: 'R-A1',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Prinsip, pola desain, dan praktik terbaik dalam menghasilkan perangkat lunak yang mudah dirawat.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0102-9',
    barcode_eksemplar: 'PS-2600003',
    judul: 'Arsitektur Microservices dengan Go & Docker',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 8,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '005.276',
    lokasi_rak: 'R-A1',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Membangun layanan terdistribusi yang tangguh dan skalabel menggunakan Golang dan kontainerisasi Docker.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0103-6',
    barcode_eksemplar: 'PS-2600004',
    judul: 'Algoritma dan Struktur Data Tingkat Lanjut',
    tahun: 2022,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 12,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '005.1',
    lokasi_rak: 'R-A2',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Studi mendalam tentang struktur graph, tree, dynamic programming, dan analisis kompleksitas algoritma.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0104-3',
    barcode_eksemplar: 'PS-2600005',
    judul: 'Belajar Machine Learning dan AI dengan Python',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 14,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '006.3',
    lokasi_rak: 'R-A2',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Konsep dasar kecerdasan buatan, regresi, klasifikasi, clustering, dan neural networks menggunakan Scikit-Learn.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0105-0',
    barcode_eksemplar: 'PS-2600006',
    judul: 'Desain Pola (Design Patterns) untuk Software Engineer',
    tahun: 2023,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 7,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '005.12',
    lokasi_rak: 'R-A2',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Implementasi praktis 23 pola desain Gang of Four (GoF) pada aplikasi modern.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0106-7',
    barcode_eksemplar: 'PS-2600007',
    judul: 'Pemrograman Android Modern dengan Kotlin & Jetpack',
    tahun: 2024,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 9,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '005.258',
    lokasi_rak: 'R-A3',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Pengembangan aplikasi mobile native Android menggunakan Jetpack Compose dan arsitektur MVVM.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0107-4',
    barcode_eksemplar: 'PS-2600008',
    judul: 'Fundamental Keamanan Jaringan dan Ethical Hacking',
    tahun: 2023,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 6,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '005.8',
    lokasi_rak: 'R-A3',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Teknik penetration testing, scanning kerentanan, enkripsi data, dan pertahanan siber.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0108-1',
    barcode_eksemplar: 'PS-2600009',
    judul: 'Cloud Computing dengan AWS dan Kubernetes',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 8,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '004.678',
    lokasi_rak: 'R-A3',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Orkestrasi kontainer skala enterprise, auto-scaling, dan deployment otomatis di cloud.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0109-8',
    barcode_eksemplar: 'PS-2600010',
    judul: 'Pengembangan Full-Stack dengan Next.js dan Tailwind CSS',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 16,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '005.276',
    lokasi_rak: 'R-A4',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Langkah praktis membangun antarmuka interaktif dan API route performa tinggi dengan React Server Components.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0110-4',
    barcode_eksemplar: 'PS-2600011',
    judul: 'Panduan Komprehensif Database PostgreSQL & Optimasi Query',
    tahun: 2023,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 11,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '005.74',
    lokasi_rak: 'R-A4',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Teknik pengindeksan b-tree, partisi tabel, query planning (EXPLAIN ANALYZE), dan tuning performa.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0111-1',
    barcode_eksemplar: 'PS-2600012',
    judul: 'Pemrograman Sistem dengan Bahasa Rust',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 7,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '005.133',
    lokasi_rak: 'R-A4',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Manajemen memori tanpa garbage collector, konsep ownership, concurrency yang aman dan performa maksimal.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0112-8',
    barcode_eksemplar: 'PS-2600013',
    judul: 'Deep Learning untuk Pengolahan Citra Digital',
    tahun: 2023,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 9,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '006.42',
    lokasi_rak: 'R-A5',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Convolutional Neural Networks (CNN), deteksi objek dengan YOLO, dan segmentasi citra medis.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0113-5',
    barcode_eksemplar: 'PS-2600014',
    judul: 'Belajar TypeScript dari Dasar hingga Mahir',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 15,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '005.133',
    lokasi_rak: 'R-A5',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Sistem tipe statis, generics, interfaces, union types, dan integrasi dengan ekosistem JavaScript.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0114-2',
    barcode_eksemplar: 'PS-2600015',
    judul: 'Rekayasa Perangkat Lunak Berbasis Agile dan Scrum',
    tahun: 2022,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 8,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '005.1',
    lokasi_rak: 'R-A5',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Manajemen siklus hidup aplikasi modern dengan sprint, backlog refinement, dan continuous delivery.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0115-9',
    barcode_eksemplar: 'PS-2600016',
    judul: 'Membangun RESTful API Skalabilitas Tinggi',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 12,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '005.276',
    lokasi_rak: 'R-A6',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Arsitektur API standar industri, rate limiting, caching Redis, OAuth2, dan dokumentasi OpenAPI/Swagger.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0116-6',
    barcode_eksemplar: 'PS-2600017',
    judul: 'Pengantar Komputasi Awan dan DevOps CI/CD',
    tahun: 2023,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 10,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '004.678',
    lokasi_rak: 'R-A6',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Otomatisasi pengujian dan deployment aplikasi menggunakan GitHub Actions, GitLab CI, dan Terraform.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0117-3',
    barcode_eksemplar: 'PS-2600018',
    judul: 'Data Engineering dengan Apache Spark dan Kafka',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 7,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '005.74',
    lokasi_rak: 'R-A6',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Pemrosesan data real-time, streaming pipeline, data lakehouse, dan transformasi data berskala petabyte.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0118-0',
    barcode_eksemplar: 'PS-2600019',
    judul: 'Pemrograman Flutter untuk Aplikasi Multiplatform',
    tahun: 2023,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 13,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '005.258',
    lokasi_rak: 'R-A7',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Satu basis kode Dart untuk aplikasi Android, iOS, web, dan desktop dengan performa 60fps.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-01-0119-7',
    barcode_eksemplar: 'PS-2600020',
    judul: 'Dasar-Dasar Grafika Komputer dan Game Engine',
    tahun: 2022,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG0',
    qty_stok: 5,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '006.6',
    lokasi_rak: 'R-A7',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Prinsip rendering 3D, pencahayaan shader, fisika game, dan pembuatan game menggunakan Unity dan Godot.',
    katalog: { id_katalog: 'KG0', nama: '000 — Komputer & Pemrograman' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },

  // =========================================================================
  // 2. TEKNOLOGI & SAINS TERAPAN (KG1) - 20 BUKU
  // =========================================================================
  {
    isbn: '978-623-22-1209-4',
    barcode_eksemplar: 'PS-2600021',
    judul: 'Ensiklopedia Sains & Teknologi Modern (Referensi)',
    tahun: 2024,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 3,
    foto: '/buku/1788322296_mieayam.jpg',
    maks_pinjam_per_anggota: 1,
    ddc: '600',
    lokasi_rak: 'R-REF1',
    kondisi: 'Baik',
    is_reference: true,
    sinopsis: 'Koleksi rujukan ensiklopedia teknologi dan inovasi mutakhir. Baca di tempat perpustakaan.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1210-0',
    barcode_eksemplar: 'PS-2600022',
    judul: 'Internet of Things (IoT) Berbasis ESP32 dan Arduino',
    tahun: 2023,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 12,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '621.39',
    lokasi_rak: 'R-B1',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Proyek praktis otomasi rumah pintar, pemantauan sensor via MQTT, dan integrasi dashboard cloud.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1211-7',
    barcode_eksemplar: 'PS-2600023',
    judul: 'Energi Terbarukan: Solar Cell dan Pembangkit Angin',
    tahun: 2024,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 8,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '621.042',
    lokasi_rak: 'R-B1',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Prinsip konversi energi fotovoltaik, turbin angin mikro, dan integrasi penyimpanan energi baterai.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1212-4',
    barcode_eksemplar: 'PS-2600024',
    judul: 'Robotika Industri dan Sistem Otomasi Pabrik',
    tahun: 2023,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 7,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '629.892',
    lokasi_rak: 'R-B1',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Kinematika lengan robot artikulasi, PLC (Programmable Logic Controller), dan sensor visi komputer pabrik.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1213-1',
    barcode_eksemplar: 'PS-2600025',
    judul: 'Fisika Terapan untuk Teknik dan Rekayasa',
    tahun: 2022,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 14,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '530.024',
    lokasi_rak: 'R-B2',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Aplikasi mekanika fluida, optika, gelombang elektromagnetik, dan kelistrikan dalam bidang keteknikan.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1214-8',
    barcode_eksemplar: 'PS-2600026',
    judul: 'Sensor Pintar dan Instrumentasi Medis',
    tahun: 2024,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 9,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '610.28',
    lokasi_rak: 'R-B2',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Pengukuran biosinyal ECG, EEG, oximetry, dan pengolahan data biomedis untuk peralatan diagnosa medis.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1215-5',
    barcode_eksemplar: 'PS-2600027',
    judul: 'Pengolahan Sinyal Digital dan Kecerdasan Buatan',
    tahun: 2023,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 8,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '621.382',
    lokasi_rak: 'R-B2',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Transformasi Fourier, filter digital IIR/FIR, analisis spektrum suara dan kompresi audio modern.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1216-2',
    barcode_eksemplar: 'PS-2600028',
    judul: 'Nanoteknologi: Masa Depan Material Cerdas',
    tahun: 2024,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 6,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '620.5',
    lokasi_rak: 'R-B3',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Sintesis karbon nanotube, graphene, dan aplikasi rekayasa material nano dalam dunia elektronik dan energi.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1217-9',
    barcode_eksemplar: 'PS-2600029',
    judul: 'Termodinamika dan Sistem Konversi Energi',
    tahun: 2022,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 11,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '621.402',
    lokasi_rak: 'R-B3',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Siklus Rankine, Brayton, Diesel, perpindahan kalor konduksi dan konveksi pada mesin pembangkit daya.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1218-6',
    barcode_eksemplar: 'PS-2600030',
    judul: 'Mekatronika: Integrasi Mekanik, Elektronik, dan Komputer',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 9,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '621.3',
    lokasi_rak: 'R-B3',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Desain aktuator hidrolik, motor stepper, mikrokontroler real-time, dan perancangan sistem servo.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1219-3',
    barcode_eksemplar: 'PS-2600031',
    judul: 'Sistem Kontrol Cerdas dan Logika Fuzzy',
    tahun: 2023,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 7,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '629.8',
    lokasi_rak: 'R-B4',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Pemodelan kendali non-linier, algoritma genetika, dan sistem penalaran fuzzy untuk aplikasi kendali presisi.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1220-9',
    barcode_eksemplar: 'PS-2600032',
    judul: 'Bioteknologi Industri dan Fermentasi Modern',
    tahun: 2024,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 8,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '660.6',
    lokasi_rak: 'R-B4',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Rekayasa enzim, bioproses bioreaktor skala komersial, dan pemanfaatan mikroorganisme industri.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1221-6',
    barcode_eksemplar: 'PS-2600033',
    judul: 'Pengantar Teknik Biomedika dan Prostetik Pintar',
    tahun: 2023,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 5,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '617.9',
    lokasi_rak: 'R-B4',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Desain prostetik tangan bionik, sensor elektromiografi (EMG), dan integrasi material biokompatibel.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1222-3',
    barcode_eksemplar: 'PS-2600034',
    judul: 'Analisis Struktur dan Kekuatan Material Logam',
    tahun: 2022,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 10,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '620.11',
    lokasi_rak: 'R-B5',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Diagram tegangan-regangan, uji fatik lelah logam, perlakuan panas baja, dan metode elemen hingga (FEA).',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1223-0',
    barcode_eksemplar: 'PS-2600035',
    judul: 'Sistem Transmisi Tenaga Listrik dan Smart Grid',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 8,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '621.319',
    lokasi_rak: 'R-B5',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Jaringan distribusi tegangan tinggi, proteksi relai digital, dan integrasi pembangkit terdesentralisasi.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1224-7',
    barcode_eksemplar: 'PS-2600036',
    judul: 'Kimia Terapan untuk Industri Lingkungan',
    tahun: 2023,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 12,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '660',
    lokasi_rak: 'R-B5',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Pengolahan air limbah industri B3, adsorpsi karbon aktif, dan teknologi bioremediasi tanah tercemar.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1225-4',
    barcode_eksemplar: 'PS-2600037',
    judul: 'Teknik Pendingin dan Tata Udara Ramah Lingkungan',
    tahun: 2024,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 7,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '621.56',
    lokasi_rak: 'R-B6',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Sistem refrigerasi kompresi uap, pemilihan refrigeran hidrokarbon ramah ozon, dan psikrometrik AC.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1226-1',
    barcode_eksemplar: 'PS-2600038',
    judul: 'Pemodelan Dinamika Fluida Komputasi (CFD)',
    tahun: 2023,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 6,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '620.106',
    lokasi_rak: 'R-B6',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Persamaan Navier-Stokes, pembuatan mesh diskritisasi, simulasi aerodinamika, dan aliran turbulen.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1227-8',
    barcode_eksemplar: 'PS-2600039',
    judul: 'Kendaraan Listrik: Baterai, Motor, dan Kontrol Daya',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 14,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '629.229',
    lokasi_rak: 'R-B6',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Battery Management System (BMS), motor sinkron magnet permanen (PMSM), dan inverter daya EV.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-623-22-1228-5',
    barcode_eksemplar: 'PS-2600040',
    judul: 'Ergonomi dan Keselamatan Kesehatan Kerja (K3)',
    tahun: 2023,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG1',
    qty_stok: 10,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '620.82',
    lokasi_rak: 'R-B7',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Identifikasi bahaya HAZOP, penataan stasiun kerja ergonomis, dan standar kepatuhan OSHA di tempat kerja.',
    katalog: { id_katalog: 'KG1', nama: '600 — Teknologi & Sains Terapan' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },

  // =========================================================================
  // 3. EKONOMI, BISNIS & SOSIAL (KG2) - 20 BUKU
  // =========================================================================
  {
    isbn: '978-602-03-3101-2',
    barcode_eksemplar: 'PS-2600041',
    judul: 'Manajemen Keuangan Korporat & Valuasi Pasar',
    tahun: 2024,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 11,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '658.15',
    lokasi_rak: 'R-C1',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Analisis discounted cash flow (DCF), penganggaran modal, struktur modal optimal, dan merger akuisisi.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3102-9',
    barcode_eksemplar: 'PS-2600042',
    judul: 'Psikologi Komunikasi dan Negosiasi Bisnis',
    tahun: 2023,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 15,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '302.2',
    lokasi_rak: 'R-C1',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Memahami bahasa tubuh, prinsip persuasi Robert Cialdini, dan strategi negosiasi win-win solution.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3103-6',
    barcode_eksemplar: 'PS-2600043',
    judul: 'Strategi Pemasaran Digital & E-Commerce 5.0',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 13,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '658.872',
    lokasi_rak: 'R-C1',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Funnel penjualan digital, Search Engine Optimization (SEO), periklanan terarah, dan analitik konversi.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3104-3',
    barcode_eksemplar: 'PS-2600044',
    judul: 'Akuntansi Keuangan Menengah Berbasis IFRS',
    tahun: 2022,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 9,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '657.044',
    lokasi_rak: 'R-C2',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Penyusunan neraca lajur, pengakuan pendapatan PSAK 72, aset tetap depresiasi, dan liabilitas jangka panjang.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3105-0',
    barcode_eksemplar: 'PS-2600045',
    judul: 'Startup Playbook: Dari Validasi Ide hingga Pendanaan',
    tahun: 2024,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 12,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '658.11',
    lokasi_rak: 'R-C2',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Metodologi lean startup, penentuan Product-Market Fit, pembuatan pitch deck, dan strategi pitching investor.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3106-7',
    barcode_eksemplar: 'PS-2600046',
    judul: 'Kepemimpinan Efektif dalam Era Transformasi Digital',
    tahun: 2023,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 14,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '658.409',
    lokasi_rak: 'R-C2',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Membangun budaya inovasi kolaboratif, memimpin tim jarak jauh, dan pengambilan keputusan berbasis data.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3107-4',
    barcode_eksemplar: 'PS-2600047',
    judul: 'Ekonomi Makro: Kebijakan Moneter dan Stabilitas Harga',
    tahun: 2022,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 10,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '339',
    lokasi_rak: 'R-C3',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Model IS-LM, pengendalian inflasi, suku bunga bank sentral, dan pertumbuhan ekonomi nasional.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3108-1',
    barcode_eksemplar: 'PS-2600048',
    judul: 'Manajemen Rantai Pasok (Supply Chain Management) Terpadu',
    tahun: 2024,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 8,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '658.7',
    lokasi_rak: 'R-C3',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Peramalan permintaan pasar, pengelolaan persediaan buffer stock, rute logistik dan pergudangan modern.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3109-8',
    barcode_eksemplar: 'PS-2600049',
    judul: 'Hukum Bisnis dan Kepatuhan Korporasi di Indonesia',
    tahun: 2023,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 7,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '346.07',
    lokasi_rak: 'R-C3',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Hukum perseroan terbatas, penyusunan kontrak perjanjian, hak kekayaan intelektual (HAKI), dan hukum ketenagakerjaan.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3110-4',
    barcode_eksemplar: 'PS-2600050',
    judul: 'Riset Pasar dan Analisis Perilaku Konsumen',
    tahun: 2024,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 11,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '658.834',
    lokasi_rak: 'R-C4',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Teknik survei kuantitatif, wawancara mendalam fokus grup, dan pemetaan customer journey pasar modern.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3111-1',
    barcode_eksemplar: 'PS-2600051',
    judul: 'Manajemen Sumber Daya Manusia Strategis',
    tahun: 2023,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 13,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '658.3',
    lokasi_rak: 'R-C4',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Perekrutan berbasis kompetensi, penilaian kinerja KPI & OKR, kompensasi karyawan, dan manajemen talenta.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3112-8',
    barcode_eksemplar: 'PS-2600052',
    judul: 'Investasi Saham dan Manajemen Portofolio Modern',
    tahun: 2024,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 16,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '332.632',
    lokasi_rak: 'R-C4',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Analisis fundamental rasio keuangan emiten, analisis teknikal candlestick, dan alokasi aset diversifikasi.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3113-5',
    barcode_eksemplar: 'PS-2600053',
    judul: 'Manajemen Risiko Operasional dan Finansial',
    tahun: 2023,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 9,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '658.155',
    lokasi_rak: 'R-C5',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Kerangka kerja ISO 31000, pemetaan matriks risiko bisnis, dan mitigasi krisis tak terduga.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3114-2',
    barcode_eksemplar: 'PS-2600054',
    judul: 'Brand Strategy: Membangun Identitas Merek Berdaya Saing',
    tahun: 2024,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 12,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '658.827',
    lokasi_rak: 'R-C5',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Mendefinisikan persona merek, diferensiasi positioning, storytelling produk, dan loyalitas konsumen jangka panjang.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3115-9',
    barcode_eksemplar: 'PS-2600055',
    judul: 'Perpajakan Indonesia: Teori dan Tata Cara Praktis',
    tahun: 2023,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 10,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '336.2',
    lokasi_rak: 'R-C5',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Penghitungan PPh pasal 21, PPh badan, PPN e-faktur, dan pelaporan SPT tahunan secara elektronik.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3116-6',
    barcode_eksemplar: 'PS-2600056',
    judul: 'Kewirausahaan Sosial dan Pemberdayaan Komunitas',
    tahun: 2022,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 8,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '361.7',
    lokasi_rak: 'R-C6',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Model bisnis berbasis dampak sosial positif, pembiayaan mikro, dan keberlanjutan ekonomi pedesaan.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3117-3',
    barcode_eksemplar: 'PS-2600057',
    judul: 'Public Relations Modern: Manajemen Krisis dan Reputasi',
    tahun: 2024,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 11,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '659.2',
    lokasi_rak: 'R-C6',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Komunikasi media massa, penanganan isu viral di media sosial, dan penulisan siaran pers profesional.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3118-0',
    barcode_eksemplar: 'PS-2600058',
    judul: 'Ekonomi Kreatif: Mengubah Gagasan Menjadi Nilai Tambah',
    tahun: 2023,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 9,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '338.47',
    lokasi_rak: 'R-C6',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Potensi 17 subsektor ekonomi kreatif, pembiayaan kreatif, dan diplomasi budaya Indonesia di kancah global.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3119-7',
    barcode_eksemplar: 'PS-2600059',
    judul: 'Perbankan Syariah: Teori, Prinsip, dan Operasional',
    tahun: 2024,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 10,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '332.109',
    lokasi_rak: 'R-C7',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Akad mudharabah, musyarakah, murabahah, ijarah, dan tata kelola kepatuhan syariah (Sharia Governance).',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-3120-3',
    barcode_eksemplar: 'PS-2600060',
    judul: 'Analisis Laporan Keuangan untuk Keputusan Bisnis',
    tahun: 2023,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG2',
    qty_stok: 12,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '657.3',
    lokasi_rak: 'R-C7',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Rasio likuiditas, solvabilitas, profitabilitas DuPont analysis, dan evaluasi kesehatan finansial perusahaan.',
    katalog: { id_katalog: 'KG2', nama: '300 — Ekonomi, Bisnis & Sosial' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },

  // =========================================================================
  // 4. PERTANIAN PRESISI & AGRO (KG3) - 20 BUKU
  // =========================================================================
  {
    isbn: '978-602-88-2101-5',
    barcode_eksemplar: 'PS-2600061',
    judul: 'Pertanian Presisi Menggunakan Drone dan Citra Satelit',
    tahun: 2024,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 11,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '631.3',
    lokasi_rak: 'R-D1',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Analisis indeks vegetasi NDVI, pemetaan kadar hara lahan, dan penyemprotan pupuk presisi berbasis drone.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2102-2',
    barcode_eksemplar: 'PS-2600062',
    judul: 'Sistem Otomasi Smart Greenhouse Berbasis Mikrokontroler',
    tahun: 2023,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 10,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '631.583',
    lokasi_rak: 'R-D1',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Pengendalian suhu mikro, kelembaban kabut (fogging), intensitas lampu growlight, dan ventilasi otomatis.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2103-9',
    barcode_eksemplar: 'PS-2600063',
    judul: 'Hidroponik dan Akuaponik Komersial Skala Urban',
    tahun: 2024,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 14,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '631.585',
    lokasi_rak: 'R-D1',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Sistem NFT (Nutrient Film Technique), Dutch Bucket, pengaturan EC & pH nutrisi AB Mix, dan simbiosis ikan air tawar.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2104-6',
    barcode_eksemplar: 'PS-2600064',
    judul: 'Manajemen Kesuburan Tanah dan Nutrisi Tanaman Tropika',
    tahun: 2022,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 9,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '631.42',
    lokasi_rak: 'R-D2',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Kimia tanah masam, kapasitas tukar kation (KTK), aplikasi kapur dolomit, dan efisiensi serapan pupuk fosfat.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2105-3',
    barcode_eksemplar: 'PS-2600065',
    judul: 'Pengendalian Hama Terpadu (PHT) Ramah Lingkungan',
    tahun: 2023,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 12,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '632.9',
    lokasi_rak: 'R-D2',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Pemanfaatan musuh alami predator parasitoid, biopestisida nabati, dan rotasi tanaman pencegah ledakan hama.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2106-0',
    barcode_eksemplar: 'PS-2600066',
    judul: 'Agribisnis Berkelanjutan dan Rantai Dingin Pangan',
    tahun: 2024,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 10,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '630.68',
    lokasi_rak: 'R-D2',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Cold chain logistic untuk produk sayur dan buah segar, sertifikasi Good Agricultural Practices (GAP).',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2107-7',
    barcode_eksemplar: 'PS-2600067',
    judul: 'Pemuliaan Tanaman Pangan dan Bioteknologi Benih Unggul',
    tahun: 2023,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 8,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '631.52',
    lokasi_rak: 'R-D3',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Persilangan hibrida varietas unggul padi dan jagung tahan kekeringan, kultur jaringan meristem.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2108-4',
    barcode_eksemplar: 'PS-2600068',
    judul: 'Irigasi Tetes Otomatis Berbasis Sensor Kelembaban Lahan',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 13,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '631.587',
    lokasi_rak: 'R-D3',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Pemasangan pipa lateral drip emitter, pompa solenoid valve terprogram, dan efisiensi penggunaan air hingga 70%.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2109-1',
    barcode_eksemplar: 'PS-2600069',
    judul: 'Teknologi Pascapanen dan Pengolahan Hasil Hortikultura',
    tahun: 2022,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 7,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '631.56',
    lokasi_rak: 'R-D3',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Pengendalian laju respirasi buah, pengemasan modified atmosphere packaging (MAP), dan pengolahan pangan kering.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2110-7',
    barcode_eksemplar: 'PS-2600070',
    judul: 'Budidaya Pertanian Organik Bersertifikasi Nasional',
    tahun: 2024,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 12,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '631.584',
    lokasi_rak: 'R-D4',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Standar SNI Organik 6729, pembuatan pupuk bokashi cair, kompos cacing vermikompos, dan audit sertifikasi.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2111-4',
    barcode_eksemplar: 'PS-2600071',
    judul: 'Agroklimatologi: Mitigasi Dampak Perubahan Iklim',
    tahun: 2023,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 9,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '630.251',
    lokasi_rak: 'R-D4',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Analisis fenomena El Nino / La Nina, penyesuaian kalender tanam, dan konservasi air waduk pertanian.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2112-1',
    barcode_eksemplar: 'PS-2600072',
    judul: 'Pengolahan Biomassa Pertanian Menjadi Biochar & Energi',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 11,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '662.88',
    lokasi_rak: 'R-D4',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Pirolisis sekam padi dan tandan kosong sawit menjadi pembenah tanah biochar penyerap karbon.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2113-8',
    barcode_eksemplar: 'PS-2600073',
    judul: 'Smart Farming: Sensor IoT Pemantauan Kesehatan Ternak',
    tahun: 2023,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 8,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '636.08',
    lokasi_rak: 'R-D5',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Ear-tag RFID pintar, sensor deteksi siklus estrus sapi perah, dan otomatisasi pakan konsentrat.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2114-5',
    barcode_eksemplar: 'PS-2600074',
    judul: 'Budidaya Ikan Air Tawar Intensif Sistem Bioflok',
    tahun: 2024,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 15,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '639.31',
    lokasi_rak: 'R-D5',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Kultur bakteri heterotrof pengurai amonia, rasio C/N pakan, aerasi kolam bundar terpal, dan budidaya lele/nila padat tebar.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2115-2',
    barcode_eksemplar: 'PS-2600075',
    judul: 'Manajemen Perkebunan Kelapa Sawit Berkelanjutan (RSPO)',
    tahun: 2023,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 10,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '633.851',
    lokasi_rak: 'R-D5',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Praktik agronomi kelapa sawit prima, konservasi sempadan sungai, penyerbukan Elaeidobius, dan sertifikasi ISPO/RSPO.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2116-9',
    barcode_eksemplar: 'PS-2600076',
    judul: 'Teknologi Benih dan Konservasi Plasma Nutfah Lokal',
    tahun: 2022,
    id_penerbit: 'PN02',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 6,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '631.521',
    lokasi_rak: 'R-D6',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Uji daya berkecambah vigor benih, penyimpanan seed bank suhu rendah, dan pelestarian varietas lokal nusantara.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN02', nama_penerbit: 'Andi Offset Yogyakarta' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2117-6',
    barcode_eksemplar: 'PS-2600077',
    judul: 'Mekanisasi Pertanian: Alat dan Mesin Panen Modern',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 9,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '631.3',
    lokasi_rak: 'R-D6',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Pengoperasian traktor roda empat, mesin combine harvester padi, dan pemeliharaan alat mesin pertanian (alsintan).',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2118-3',
    barcode_eksemplar: 'PS-2600078',
    judul: 'Ekonomi Pertanian dan Ketahanan Pangan Nasional',
    tahun: 2023,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 12,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '338.1',
    lokasi_rak: 'R-D6',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Struktur subsidi pupuk, stabilisasi harga gabah di tingkat petani, tata niaga komoditas, dan lumbung pangan.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2119-0',
    barcode_eksemplar: 'PS-2600079',
    judul: 'Sistem Informasi Geografis (SIG) untuk Pemetaan Lahan',
    tahun: 2024,
    id_penerbit: 'PN01',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 10,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '910.285',
    lokasi_rak: 'R-D7',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Penggunaan QGIS untuk overlay peta kemiringan lereng, kesesuaian komoditas tanaman, dan tata ruang wilayah agro.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN01', nama_penerbit: 'Informatika Bandung' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-88-2120-6',
    barcode_eksemplar: 'PS-2600080',
    judul: 'Budidaya Kopi Spesialti dan Teknik Pasca Panen Modern',
    tahun: 2023,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG3',
    qty_stok: 16,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '633.73',
    lokasi_rak: 'R-D7',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Fermentasi anaerobik ceri kopi, proses natural/honey/washed, pengujian cupping score SCAA, dan profil roasting.',
    katalog: { id_katalog: 'KG3', nama: '630 — Pertanian Presisi & Agro' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },

  // =========================================================================
  // 5. SASTRA, FIKSI & HUMANIORA (KG4) - 20 BUKU
  // =========================================================================
  {
    isbn: '978-623-01-0812-7',
    barcode_eksemplar: 'PS-2600081',
    judul: 'Bumi Manusia (Tetralogi Buru Buku 1)',
    tahun: 2024,
    id_penerbit: 'PN03',
    id_pengarang: 'PG02',
    id_katalog: 'KG4',
    qty_stok: 12,
    foto: '/buku/1788321818_Gemini_Generated_Image_q4cmfbq4cmfbq4cm1.jpg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E1',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Kisah Minke di masa kolonial Hindia Belanda dengan perjuangan kemanusiaan, cinta, dan harga diri.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG02', nama_pengarang: 'Pramoedya Ananta Toer' },
  },
  {
    isbn: '978-979-22-2102-1',
    barcode_eksemplar: 'PS-2600082',
    judul: 'Anak Semua Bangsa (Tetralogi Buru Buku 2)',
    tahun: 2023,
    id_penerbit: 'PN03',
    id_pengarang: 'PG02',
    id_katalog: 'KG4',
    qty_stok: 10,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E1',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Kesadaran kebangsaan Minke mulai terbuka lebar melihat penderitaan rakyat jelata di pedesaan Jawa.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG02', nama_pengarang: 'Pramoedya Ananta Toer' },
  },
  {
    isbn: '978-979-22-2103-8',
    barcode_eksemplar: 'PS-2600083',
    judul: 'Jejak Langkah (Tetralogi Buru Buku 3)',
    tahun: 2023,
    id_penerbit: 'PN03',
    id_pengarang: 'PG02',
    id_katalog: 'KG4',
    qty_stok: 9,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E1',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Langkah Minke mendirikan surat kabar pribumi pertama Medan Priyayi dan organisasi pergerakan modern.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG02', nama_pengarang: 'Pramoedya Ananta Toer' },
  },
  {
    isbn: '978-979-22-2104-5',
    barcode_eksemplar: 'PS-2600084',
    judul: 'Rumah Kaca (Tetralogi Buru Buku 4)',
    tahun: 2022,
    id_penerbit: 'PN03',
    id_pengarang: 'PG02',
    id_katalog: 'KG4',
    qty_stok: 8,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E2',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Operasi intelijen kolonial Pangemanann dalam mengawasi dan memadamkan bara perlawanan tokoh pergerakan.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG02', nama_pengarang: 'Pramoedya Ananta Toer' },
  },
  {
    isbn: '978-979-29-5321-1',
    barcode_eksemplar: 'PS-2600085',
    judul: 'Laskar Pelangi',
    tahun: 2023,
    id_penerbit: 'PN03',
    id_pengarang: 'PG03',
    id_katalog: 'KG4',
    qty_stok: 15,
    foto: '/buku/1788322287_istockphoto-1726263781-612x612.jpg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E2',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Kisah perjuangan sepuluh anak di Belitung dalam meraih pendidikan dan memelihara mimpi besar.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG03', nama_pengarang: 'Andrea Hirata' },
  },
  {
    isbn: '978-979-30-6292-1',
    barcode_eksemplar: 'PS-2600086',
    judul: 'Sang Pemimpi (Tetralogi Laskar Pelangi Buku 2)',
    tahun: 2023,
    id_penerbit: 'PN03',
    id_pengarang: 'PG03',
    id_katalog: 'KG4',
    qty_stok: 11,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E2',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Masa remaja Ikal, Arai, dan Jimbron saat menempuh SMA di Manggar dan impian menginjakkan kaki di Sorbonne.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG03', nama_pengarang: 'Andrea Hirata' },
  },
  {
    isbn: '978-979-30-6293-8',
    barcode_eksemplar: 'PS-2600087',
    judul: 'Edensor (Tetralogi Laskar Pelangi Buku 3)',
    tahun: 2022,
    id_penerbit: 'PN03',
    id_pengarang: 'PG03',
    id_katalog: 'KG4',
    qty_stok: 9,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E3',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Petualangan Ikal dan Arai menjelajahi benua Eropa dan Afrika sebagai mahasiswa beasiswa di Paris.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG03', nama_pengarang: 'Andrea Hirata' },
  },
  {
    isbn: '978-979-30-6294-5',
    barcode_eksemplar: 'PS-2600088',
    judul: 'Maryamah Karpov (Tetralogi Laskar Pelangi Buku 4)',
    tahun: 2022,
    id_penerbit: 'PN03',
    id_pengarang: 'PG03',
    id_katalog: 'KG4',
    qty_stok: 7,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E3',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Ikal kembali ke kampung halaman untuk merakit perahu demi menyelamatkan cinta sejatinya, A Ling.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG03', nama_pengarang: 'Andrea Hirata' },
  },
  {
    isbn: '978-602-03-1201-1',
    barcode_eksemplar: 'PS-2600089',
    judul: 'Cantik Itu Luka',
    tahun: 2024,
    id_penerbit: 'PN03',
    id_pengarang: 'PG02',
    id_katalog: 'KG4',
    qty_stok: 14,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E3',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Kisah magis-realis Dewi Ayu dan kutukan kecantikan di kota fiktif Halimunda sepanjang sejarah Indonesia.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG02', nama_pengarang: 'Pramoedya Ananta Toer' },
  },
  {
    isbn: '978-602-03-1202-8',
    barcode_eksemplar: 'PS-2600090',
    judul: 'Lelaki Harimau',
    tahun: 2023,
    id_penerbit: 'PN03',
    id_pengarang: 'PG02',
    id_katalog: 'KG4',
    qty_stok: 10,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E4',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Misteri pembunuhan Anwar Sadat oleh Margio yang di dalam tubuhnya bersemayam harimau putih gaib.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG02', nama_pengarang: 'Pramoedya Ananta Toer' },
  },
  {
    isbn: '978-602-03-1203-5',
    barcode_eksemplar: 'PS-2600091',
    judul: 'Gadis Kretek',
    tahun: 2023,
    id_penerbit: 'PN03',
    id_pengarang: 'PG03',
    id_katalog: 'KG4',
    qty_stok: 18,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E4',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Romansa berlatar sejarah industri kretek Nusantara dan rahasia racikan saus rokok legendaris Jeng Yah.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG03', nama_pengarang: 'Andrea Hirata' },
  },
  {
    isbn: '978-602-03-1204-2',
    barcode_eksemplar: 'PS-2600092',
    judul: 'Laut Bercerita',
    tahun: 2024,
    id_penerbit: 'PN03',
    id_pengarang: 'PG02',
    id_katalog: 'KG4',
    qty_stok: 20,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E4',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Kisah aktivis mahasiswa Biru Laut yang diculik pada masa Orde Baru serta ketabahan keluarga korban penghilangan paksa.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG02', nama_pengarang: 'Pramoedya Ananta Toer' },
  },
  {
    isbn: '978-602-03-1205-9',
    barcode_eksemplar: 'PS-2600093',
    judul: 'Pulang (Kisah Eksil Politik di Paris)',
    tahun: 2023,
    id_penerbit: 'PN03',
    id_pengarang: 'PG02',
    id_katalog: 'KG4',
    qty_stok: 11,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E5',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Perjalanan wartawan Indonesia yang terdampar di Paris akibat tragedi 1965 dan kerinduan abadi akan tanah air.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG02', nama_pengarang: 'Pramoedya Ananta Toer' },
  },
  {
    isbn: '978-602-03-1206-6',
    barcode_eksemplar: 'PS-2600094',
    judul: 'Ronggeng Dukuh Paruk',
    tahun: 2022,
    id_penerbit: 'PN03',
    id_pengarang: 'PG02',
    id_katalog: 'KG4',
    qty_stok: 10,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E5',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Trilogi Srintil sebagai ronggeng terpilih di desa miskin Dukuh Paruk yang terseret pusaran pergolakan politik 1965.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG02', nama_pengarang: 'Pramoedya Ananta Toer' },
  },
  {
    isbn: '978-602-03-1207-3',
    barcode_eksemplar: 'PS-2600095',
    judul: 'Hujan Bulan Juni: Kumpulan Sajak Pilihan',
    tahun: 2024,
    id_penerbit: 'PN03',
    id_pengarang: 'PG02',
    id_katalog: 'KG4',
    qty_stok: 15,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E5',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Kumpulan puisi liris legendaris karya Sapardi Djoko Damono yang abadi tentang cinta, ketabahan, dan keheningan.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG02', nama_pengarang: 'Pramoedya Ananta Toer' },
  },
  {
    isbn: '978-602-03-1208-0',
    barcode_eksemplar: 'PS-2600096',
    judul: 'Saman (Karya Ayu Utami)',
    tahun: 2023,
    id_penerbit: 'PN03',
    id_pengarang: 'PG02',
    id_katalog: 'KG4',
    qty_stok: 8,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E6',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Novel pendobrak sastra Indonesia era reformasi mengenai kebebasan nurani, spiritualitas, dan tabu sosial.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG02', nama_pengarang: 'Pramoedya Ananta Toer' },
  },
  {
    isbn: '978-602-03-1209-7',
    barcode_eksemplar: 'PS-2600097',
    judul: 'Olenka (Karya Klasik Budi Darma)',
    tahun: 2022,
    id_penerbit: 'PN03',
    id_pengarang: 'PG02',
    id_katalog: 'KG4',
    qty_stok: 7,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '899.221',
    lokasi_rak: 'R-E6',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Eksplorasi psikologis dan kesunyian manusia modern di Bloomington melalui sosok perempuan misterius Olenka.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG02', nama_pengarang: 'Pramoedya Ananta Toer' },
  },
  {
    isbn: '978-602-03-1210-3',
    barcode_eksemplar: 'PS-2600098',
    judul: 'Filosofi Teras: Filsafat Stoikisme untuk Mental Tangguh',
    tahun: 2024,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG4',
    qty_stok: 22,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '188',
    lokasi_rak: 'R-E6',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Penerapan praktis filsafat Stoa kuno untuk mengatasi kecemasan hidup, overthinking, dan melatih ketenangan batin.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-1211-0',
    barcode_eksemplar: 'PS-2600099',
    judul: 'Atomic Habits: Perubahan Kecil yang Mengubah Hidup',
    tahun: 2024,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG4',
    qty_stok: 1, // 1 dipinjam (bisa diuji kembali di Mode Kembali F2)
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '158.1',
    lokasi_rak: 'R-E7',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Sistem pembentukan kebiasaan positif 1% setiap hari berdasarkan sains perilaku dan neurobiologi modern.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
  {
    isbn: '978-602-03-1212-7',
    barcode_eksemplar: 'PS-2600100',
    judul: 'Sapiens: Riwayat Singkat Umat Manusia',
    tahun: 2024,
    id_penerbit: 'PN03',
    id_pengarang: 'PG01',
    id_katalog: 'KG4',
    qty_stok: 18,
    foto: '/default-book-cover.svg',
    maks_pinjam_per_anggota: 2,
    ddc: '909',
    lokasi_rak: 'R-E7',
    kondisi: 'Baik',
    is_reference: false,
    sinopsis: 'Evolusi Homo sapiens dari kera tak berarti hingga menjadi penguasa planet bumi melalui tiga revolusi besar.',
    katalog: { id_katalog: 'KG4', nama: '800 — Sastra & Fiksi' },
    penerbit: { id_penerbit: 'PN03', nama_penerbit: 'Pustaka Gramedia' },
    pengarang: { id_pengarang: 'PG01', nama_pengarang: 'Budi Raharjo' },
  },
];
